import "./assets/css/all.min.css";
import "./assets/css/animate.css";
import "./assets/css/bootstrap.min.css";
import "./assets/css/icofont.min.css";
import "./assets/css/lightcase.css";
import "./assets/css/swiper.min.css";
import "./assets/css/style.css";
import "./assets/css/style.css.map";
import "./assets/css/odometer.css";

const Contact = () => {
  return (
    <div id="terms-and-conditions" className="pt-150">
      <div className="container-fluid">
        <div className="row terms-and-conditions-section">
          <div className="col-xs-12 text-center">
            <h1 className="title">Terms and Conditions</h1>
          </div>

          <div className="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 pt-150">
            <div className="content">
              <p>
                Mentaluz, SRL (&quot;Mentaluz&quot;) operates Mentaluz.com (as defined below), your use of Mentaluz.com is governed by these Terms of Service (&quot;Terms&quot;), and your use of Mentaluz.com constitutes your acceptance of the Terms.
              </p>
              <p>
                &quot;Mentaluz.com&quot; (the &quot;Service&quot;) means Mentaluz.com project made available at <a href="https://Mentaluz.com">https://Mentaluz.com</a> (the “Site”) and any other software, sites, and services offered by Mentaluz in connection therewith but does not include any sites, services, products, or offerings governed by other terms of use, or, other agreements between you and Mentaluz. &quot;Customer Data&quot; means any data you make available to Mentaluz or Mentaluz from your GitHub account for the purpose of using Mentaluz. &quot;Content&quot; means all content generated by Mentaluz on your behalf (including metric data) and does not include Customer Data.
              </p>
              <p>
                We will endeavor to provide you with notice about major changes to the Terms or Mentaluz and other changes (via email to the address on your account), but we make no guarantees. Other changes could be, without limitation, changes to payment policies, security patches, added or removed functionality, and other enhancements or restrictions to Mentaluz. Your use of Mentaluz after the Terms have changed constitutes your acceptance of the Terms as changed. You may reject changes to the Terms by terminating your subscription in accordance with the &quot;Cancellation and Termination&quot; section of these Terms of Service. Mentaluz shall not be liable to you or to any third party for any change to Mentaluz.com.
              </p>
              <p>
                Please use Mentaluz.com responsibly and in compliance with these Terms. If you don&apos;t, we reserve the right to terminate your subscription in accordance with the &quot;Cancellation and Termination&quot; section of these Terms of Service.
              </p>
              <br />
              <h2 className="section-title">1. Use of Mentaluz</h2>
              <p>
                To use Mentaluz, you must (i) have a account (ii) authorize Mentaluz to access your Customer Data to provide Mentaluz, (iii) provide accurate account information any time you register to use Mentaluz, (iv) provide accurate account information when you register to use Mentaluz, and (v) be a human over the age of 13. Uses by automated methods are not permitted. You grant Mentaluz a non-exclusive, royalty-free, and worldwide license to use, store, and copy your Customer Data in order to provide Mentaluz.
              </p>
              <p>
                You are responsible for the security of your passwords and for any use of your account. You may not allow multiple people to use the same account or otherwise access Mentaluz in a manner intended to avoid incurring fees.
              </p>
              <p>
                You must comply with all applicable GitHub policies and terms of service. Mentaluz is not responsible for any acts or omissions of GitHub whether related to your account or otherwise.
              </p>
              <p>
                Mentaluz reserves the right to enforce quotas and usage limits (to any resources, including the API) at its sole discretion, with or without notice, which may result in Mentaluz disabling or throttling your usage of the Service for any amount of time.
              </p>
              <p>
                You are responsible for obtaining access to Mentaluz and that access may involve third party fees (such as Internet service provider or airtime charges). You are responsible for those fees. In addition, you must provide and are responsible for all equipment necessary to access the Site.
              </p>
              <p>
                You may not use Mentaluz:
              </p>
              <ul>
                <li>
                  for any illegal purpose, in any manner inconsistent with applicable laws, regulations, or ordinances, or to submit, post, upload, or otherwise transmit any Customer Data or Content that is unlawful, defamatory, libelous, invasive of another&apos;s privacy, abusive, threatening, harassing, vulgar, obscene, indecent or otherwise objectionable;
                </li>
                <li>
                  to submit, post, upload or otherwise transmit any Customer Data or Content that infringes or otherwise violates the rights of any third party, including without limitation privacy rights, fiduciary rights and proprietary rights;
                </li>
                <li>
                  to submit, post, upload or otherwise transmit Customer Data or Content that contains viruses, corrupted files, or any other similar software or programs that may damage the operation of Mentaluz or another person&apos;s computer; or
                </li>
                <li>
                  if you are a person barred from receiving Mentaluz under the laws of the United States or other countries, including the country in which you are resident or from which you use Mentaluz.
                </li>
              </ul>
              <br />
              <h2 className="section-title">2. Cancellation and Termination</h2>
              <p>
                To cancel your subscription, account, and access to Mentaluz, send us an email at <a href="mailto:hi@tryprojecthub.com?Subject=Cancel+Subscription">hi@tryprojecthub.com</a> instructing us to do so or cancel via the functionality on the Waffle website. If you paid for your subscription, Mentaluz is not obligated to provide any refunds if you cancel your subscription or if Mentaluz terminates your subscription because you breached these Terms. If your subscription is cancelled or terminated in accordance with the foregoing before the end of the current paid-up month, your cancellation will take effect immediately and you will not be charged again. All of your Customer Data and Content will, within a reasonable amount of time to be determined solely by Mentaluz, be deleted from Mentaluz upon cancellation.
              </p>
              <p>
                You agree that Mentaluz, in its sole discretion and for any or no reason, may terminate or suspend your account. You agree that any termination of your access to the Service may be without prior notice, and you agree that Mentaluz will not be liable to you or any third party for such termination. If you paid for your subscription, and Mentaluz did not terminate or suspend your account due to your breach of these Terms, Mentaluz will provide a pro-rata refund of unused subscription fees if it terminates or suspends your account in accordance with this paragraph.
              </p>
              <br />
              <h2 className="section-title">3. Customer Data</h2>
              <p>
                Mentaluz claims no ownership or control over any Customer Data. Except for the license expressly granted by you to Mentaluz to provide Mentaluz, you retain all right, title, and interest in and to Customer Data and you are responsible for protecting those rights and interests, as appropriate. Notwithstanding the foregoing, you grant to Mentaluz for its use a worldwide, non-exclusive, royalty-free license to aggregate or compile Customer Data with customer data of other users of Mentaluz so long as such aggregation or compilation omits any data that would enable the identification of you (“Aggregated Data”). Mentaluz shall have a worldwide, perpetual, royalty-free license to use, modify, distribute and create derivative works based on such Aggregated Data, and as between you and Mentaluz, Mentaluz shall own all compilations of the Aggregated Data, including all reports, statistics or analyses created or derived therefrom.
              </p>
              <p>
                You understand that projects in Mentaluz will display Customer Data to you and any collaborators that you designate for that project. You are solely responsible for any collaborators and third-parties (including third-party services) that you allow to view Customer Data and entrust them at your own risk.
              </p>
              <p>
                You are solely responsible for configuring Mentaluz to allow appropriate access to your Customer Data. Mentaluz is not responsible if you fail to configure, or misconfigure, your project and inadvertently allow unauthorized parties to view any Customer Data.
              </p>
              <br />
              <h2 className="section-title">4. Ideas and Feedback</h2>
              <p>
                As part of your use of Mentaluz, you may choose, or we may invite you, to submit comments, feedback or ideas about Mentaluz, including but not limited to ideas about improving Mentaluz or our other offerings (&quot;Ideas&quot;). You hereby grant Mentaluz a perpetual, royalty-free, unlimited, worldwide license to use and/or incorporate such Ideas into any Mentaluz offering (including Mentaluz) at any time in Mentaluz’s sole discretion. Ideas you submit will not be afforded any confidential treatment by Mentaluz, regardless of whether you request such treatment or otherwise designate Ideas as proprietary or confidential.
              </p>
              <br />
              <h2 className="section-title">5. External Sites and Content</h2>
              <p>
                The Mentaluz may contain links to other websites or content (“Third Party Sites”). Mentaluz does not endorse, sanction or verify the accuracy or ownership of the information contained in/on any Third Party Site or any products or services advertised on Third Party Sites. If you decide to leave the Site and navigate to Third Party Sites, or install any software or download content from any such Third Party Sites, you do so at your own risk. Once you access a Third Party Site through a link on our Site, you may be subject to the terms and conditions of such Third Party Site. You should review the applicable policies, including privacy and data gathering practices, of any Third Party Site to which you navigate from the Site, or relating to any software you use or install from a Third Party Site, including any applicable license agreement. Concerns regarding a Third Party Site should be directed to the Third Party Site itself. Mentaluz bears no responsibility for any action associated with any Third Party Site.
              </p>
              <br />
              <h2 className="section-title">6. License and Restrictions</h2>
              <p>
                Subject to and conditioned upon your agreement to and compliance with these Terms, we will make Mentaluz available to you on a subscription basis solely for your own use and not for resale or to provide services to any third party.
              </p>
              <p>
                Excluding Third Party Sites and their related content, all of the content available on or through Mentaluz, including without limitation, text, photographs, graphics, logos, trade/service marks, and/or audiovisual content, but expressly excluding Customer Data, is owned and/or controlled by Mentaluz, its licensors or Mentaluz users and is protected, as applicable, by copyright, trademark, trade dress, patent, and trade secret laws, other proprietary rights, and international treaties. You acknowledge that Mentaluz and any underlying technology or software used in connection with Mentaluz contain our proprietary information.
              </p>
              <p>
                You will not, nor will you attempt to (or allow anyone else to or attempt to):
              </p>
              <ul>
                <li>
                  copy, modify, create a derivative work of, reverse engineer, decompile or otherwise attempt to extract the source code of Mentaluz or any part thereof;
                </li>
                <li>
                  attempt to disable or circumvent any security or verification mechanism used by Mentaluz;
                </li>
                <li>
                  use Mentaluz in any manner, or otherwise engage in any activity, that could damage, disable, overburden or impair our servers or networks, or interfere with or disrupt Mentaluz or any other users&apos; use or enjoyment of Mentaluz.
                </li>
                <li>
                  attempt to gain unauthorized access to any of Mentaluz, member accounts, or computer systems or networks, through hacking, password mining or any other means.
                </li>
                <li>
                  remove any notices of copyright, trademark or other proprietary rights contained in/on or accessible through Mentaluz or in any content or other material obtained via Mentaluz;
                </li>
                <li>
                  use any robot, spider, website search/retrieval application, or other automated device, process or means to access, retrieve or index any portion of Mentaluz;
                </li>
                <li>
                  reformat or frame any portion of the web pages that are part of Mentaluz;
                </li>
                <li>
                  use Mentaluz for commercial purposes not permitted under these Terms;
                </li>
                <li>
                  in connection with your use of Mentaluz, make unauthorized use of others’ GitHub accounts or Customer Data;
                </li>
                <li>
                  create user accounts by automated means or under false or fraudulent pretenses;
                </li>
                <li>
                  provide or use tracking or monitoring functionality in connection with Mentaluz, including, without limitation, to identify other users’ actions or activities;
                </li>
                <li>
                  impersonate or attempt to impersonate any other person or entity, including without limitation Mentaluz or any employee, contractor or associate of Mentaluz; or
                </li>
                <li>
                  collect or store personal data about other users in connection with the prohibited activities described in this paragraph.
                </li>
              </ul>
              <br />
              <h2 className="section-title">7. Open Source Software</h2>
              <p>
                Open source software licenses for components of Mentaluz released under an open source license constitute separate written agreements. To the limited extent that the open source software licenses expressly supersede these Terms, the open source licenses govern your agreement with Mentaluz only for the use of the components of Mentaluz released under an open source license.
              </p>
              <br />
              <h2 className="section-title">8. Monitoring of Content</h2>
              <p>
                You understand that Mentaluz may access and disclose Customer Data or otherwise provide third parties access to it for the following reasons:
              </p>
              <ul>
                <li>
                  to send an email message to you upon your request;
                </li>
                <li>
                  to maintain the Site and Mentaluz and to develop new and useful features and services;
                </li>
                <li>
                  to follow a court order, subpoena, complaint or a lawful request from governmental authorities;
                </li>
                <li>
                  to enforce these Terms;
                </li>
                <li>
                  to respond to claims that any Customer Data or Content violates third party rights;
                </li>
                <li>
                  to respond to your requests for customer service; and
                </li>
                <li>
                  to protect the rights, property, or personal safety of Mentaluz, users of Mentaluz’s offerings, including without limitation Mentaluz, and the public.
                </li>
              </ul>
              <br />
              <h2 className="section-title">9. Our Copyright Dispute Policy</h2>
              <p>
                Mentaluz respects the intellectual property of others and requires that our users do the same. If you believe that material or content residing on or accessible through Mentaluz infringes a copyright, please send a notice of copyright infringement containing the following information to the Designated Copyright Agent listed below:
              </p>
              <ul>
                <li>
                  identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works are covered by a single notification, a representative list of such works;
                </li>
                <li>
                  identification of the claimed infringing material and information reasonably sufficient to permit us to locate the material on Mentaluz (providing the URL(s) of the claimed infringing material satisfies this requirement);
                </li>
                <li>
                  information reasonably sufficient to permit us to contact you, such as an address, telephone number, and an email address;
                </li>
                <li>
                  a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law;
                </li>
                <li>
                  a statement by you, made under penalty of perjury, that the above information in your notification is accurate and that you are the copyright owner or are authorized to act on the copyright owner&apos;s behalf; and
                </li>
                <li>
                  your physical or electronic signature.
                </li>
              </ul>
              <p>
                Our Designated Copyright Agent for notification of claimed infringement can be reached by email at: info@mentaluz.com
              </p>
              <p>
                <b>Disclaimer of Warranties:</b>
              </p>
              <p>
                IF YOU ACCESS Mentaluz, YOU DO SO AT YOUR OWN RISK. WE PROVIDE Mentaluz “AS IS,” “WITH ALL FAULTS” AND “AS AVAILABLE.” WE MAKE NO EXPRESS OR IMPLIED WARRANTIES OR GUARANTEES ABOUT Mentaluz. TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE HEREBY DISCLAIM ALL SUCH WARRANTIES, INCLUDING ALL STATUTORY WARRANTIES, WITH RESPECT TO Mentaluz, INCLUDING WITHOUT LIMITATION ANY WARRANTIES THAT Mentaluz IS MERCHANTABLE, OF SATISFACTORY QUALITY, ACCURATE, FIT FOR A PARTICULAR PURPOSE OR NEED, OR NON-INFRINGING. WE DO NOT GUARANTEE THAT THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF Mentaluz WILL BE EFFECTIVE, RELIABLE OR ACCURATE OR WILL MEET YOUR REQUIREMENTS. WE DO NOT GUARANTEE THAT YOU WILL BE ABLE TO ACCESS OR USE Mentaluz (EITHER DIRECTLY OR THROUGH THIRD-PARTY NETWORKS) AT TIMES OR LOCATIONS OF YOUR CHOOSING. WE ARE NOT RESPONSIBLE FOR THE ACCURACY, RELIABILITY, TIMELINESS OR COMPLETENESS OF INFORMATION PROVIDED BY ANY OTHER USERS OF Mentaluz OR ANY OTHER DATA OR INFORMATION PROVIDED OR RECEIVED THROUGH Mentaluz. EXCEPT AS EXPRESSLY SET FORTH HEREIN, Mentaluz MAKES NO WARRANTIES ABOUT THE INFORMATION SYSTEMS, SOFTWARE AND FUNCTIONS MADE ACCESSIBLE BY OR THROUGH Mentaluz OR ANY SECURITY ASSOCIATED WITH THE TRANSMISSION OF SENSITIVE INFORMATION. Mentaluz DOES NOT WARRANT THAT Mentaluz WILL OPERATE ERROR-FREE, THAT ERRORS IN THE SERVICE WILL BE FIXED, THAT LOSS OF DATA WILL NOT OCCUR, OR THAT Mentaluz IS FREE OF COMPUTER VIRUSES, CONTAMINANTS OR OTHER HARMFUL ITEMS. UNDER NO CIRCUMSTANCES WILL Mentaluz, ANY OF OUR AFFILIATES, DISTRIBUTORS, PARTNERS, LICENSORS, AND/OR ANY OF OUR OR THEIR DIRECTORS, OFFICERS, EMPLOYEES, CONSULTANTS, AGENTS, OR OTHER REPRESENTATIVES BE LIABLE FOR ANY LOSS OR DAMAGE CAUSED BY YOUR RELIANCE ON INFORMATION OBTAINED THROUGH THE SERVICE.
              </p>
              <br />
              <h2 className="section-title">10. Limitations on Liability</h2>
              <p>
                YOUR SOLE AND EXCLUSIVE REMEDY FOR ANY DISPUTE WITH US IS THE CANCELLATION OF YOUR USE OF Mentaluz. IN NO EVENT SHALL WE BE LIABLE TO YOU (OR TO ANY THIRD PARTY CLAIMING UNDER OR THROUGH YOU) FOR ANY DAMAGES WHATSOEVER, INCLUDING, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, PUNITIVE OR EXEMPLARY DAMAGES OR ANY BODILY INJURY, EMOTIONAL DISTRESS, DEATH OR ANY OTHER DAMAGES ARISING FROM YOUR USE OF OR INABILITY TO USE Mentaluz, WHETHER ON-LINE OR OFF-LINE, OR OTHERWISE IN CONNECTION WITH Mentaluz. THESE EXCLUSIONS APPLY TO ANY CLAIMS FOR LOST PROFITS, LOST DATA, LOSS OF GOODWILL OR BUSINESS REPUTATION, COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, WORK STOPPAGE, COMPUTER FAILURE OR MALFUNCTION, ANY OTHER COMMERCIAL DAMAGES OR LOSSES, OR ANY PERSONAL INJURY OR PROPERTY DAMAGES, EVEN IF WE KNEW OR SHOULD HAVE KNOWN OF THE POSSIBILITY OF SUCH DAMAGES. Mentaluz’S LIABILITY UNDER THESE TERMS SHALL BE LIMITED TO THE FEES YOU PAID Mentaluz IN THE TWELVE MONTHS PRIOR TO THE DATE THE CLAIM AROSE. BECAUSE SOME STATES OR JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR THE LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, IN SUCH STATES OR JURISDICTIONS, OUR LIABILITY SHALL BE LIMITED TO THE EXTENT PERMITTED BY LAW.
              </p>
              <br />
              <h2 className="section-title">11. Indemnification</h2>
              <p>
                You agree to hold harmless and indemnify Mentaluz, and its subsidiaries, affiliates, officers, agents, employees, advertisers, licensors, suppliers or partners from and against any third party claim arising from or in any way related to (a) your breach of the Terms, (b) your use of Mentaluz, (c) your violation of applicable laws, rules or regulations in connection with Mentaluz, or (d) your Customer Data, including any liability or expense arising from all claims, losses, damages (actual and consequential), suits, judgments, litigation costs and attorneys&apos; fees, of every kind and nature. In such a case, Mentaluz will provide you with written notice of such claim, suit or action.
              </p>
              <br />
              <h2 className="section-title">12. Choice of Law and Dispute Resolution</h2>
              <p>
                These Terms will be governed by and construed in accordance with the laws of the State of California without giving effect to principles of conflict of laws, and the parties consent to the jurisdiction of the federal courts of the State of California. Each party irrevocably submits to the jurisdiction and venue of any such court in any such action or proceeding. The United Nations Convention on Contracts for the International Sale of Goods will not apply to These Terms.
              </p>
              <br />
              <h2 className="section-title">13. General Legal Terms</h2>
              <p>
                These Terms constitute the whole legal agreement between you and Mentaluz and govern your use of the Service and completely replace any prior agreements between you and Mentaluz, written or oral, in relation to Mentaluz.
              </p>
              <p>
                If any part of the Terms is held invalid or unenforceable, that portion shall be construed in a manner consistent with applicable law to reflect, as nearly as possible, the original intentions of the parties, and the remaining portions shall remain in full force and effect.
              </p>
              <p>
                The failure of Mentaluz to exercise or enforce any right or provision of the Terms shall not constitute a waiver of such right or provision.
              </p>
              <p>
                Mentaluz shall not be liable for failing or delaying performance of its obligations resulting from any condition beyond its reasonable control, including but not limited to, governmental action, acts of terrorism, earthquake, fire, flood or other acts of God, labor conditions, power failures, and Internet disturbances.
              </p>
              <p>
                Mentaluz may assign this contract at any time to any parent, subsidiary, or any affiliated company, or as part of the sale to, merger with, or other transfer of our company to another entity. You may not assign these Terms.
              </p>

            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Contact;
